name:                hask-gemm-benches
version:             0.1.0.0
github:              "StarOrpheus/hask-gemm-benches"
license:             BSD3
author:              "Zakhar Koval"
maintainer:          "ellesterate@gmail.com"
copyright:           "2021 Zakhar Koval"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hask-gemm-benches#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  hask-gemm-benches-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vector
    - random
    - vector-split
    - criterion
